"""empty message

Revision ID: 96078fe75de2
Revises: ec7dee99924f
Create Date: 2016-10-13 19:14:29.090606

"""

# revision identifiers, used by Alembic.
revision = '96078fe75de2'
down_revision = 'ec7dee99924f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('title', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'title')
    ### end Alembic commands ###
